#!/usr/bin/env sh

# Determine mode
if [ "$(readlink ~/.Xresources.colors)" = ".Xresources.light" ]; then
  background=dark
else
  background=light
fi

# A specific mode (light/dark) can be forced from the command line
if [ -n "$1" ] && [ "$1" != "$background" ]; then
  # This is not that intuitive but if the requested mode is different from the
  # next mode then the _current_ mode is the same as the requested one and there
  # is nothing to do
  exit 0
fi

# Update color files
# i3 and other applications that use X resources. The symlink is used to load
# the correct color scheme on startup (.Xresources includes .Xresources.colors
# via #include .Xresources.colors)
ln -sf ".Xresources.$background" ~/.Xresources.colors

# Overwrite color configuration
xrdb -merge ~/.Xresources.colors

# Vim watches ~/.vimrc.color and reloads itself
# echo "set background=$background" > ~/.vimrc.color

# Rofi
# echo "solarized-$background" > ~/.config/rofi/theme

# For triggering dark themes in GTK apps. Requires `gnome-themes-extra` to be
# installed (for adwaita-dark). This is primarily for Firefox
if [ $background = dark ]; then
  xfconf-query --create --type string -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
else
  xfconf-query --create --type string -c xsettings -p /Net/ThemeName -s "Adwaita"
fi

# Reload
# Update WM background
hsetroot -solid "$(xrdb -query | grep 'background' | head -n1 | cut -f 2)"

# Update i3
i3-msg reload

# Update terminal emulator
# kitty +kitten themes --reload-in=all "Solarized $(echo $background | sed 's/./\U&/')"


