#!/usr/bin/env sh

# Determine mode
if [ "$(readlink ~/.Xresources.colors)" = ".Xresources.light" ]; then
  background=dark
else
  background=light
fi

# A specific mode (light/dark) can be forced from the command line
if [ -n "$1" ] && [ "$1" != "$background" ]; then
  # This is not that intuitive but if the requested mode is different from the
  # next mode then the _current_ mode is the same as the requested one and there
  # is nothing to do
  exit 0
fi

# Update color files
# i3 and other applications that use X resources. The symlink is used to load
# the correct color scheme on startup (.Xresources includes .Xresources.colors
# via #include .Xresources.colors)
ln -sf ".Xresources.$background" ~/.Xresources.colors

# Overwrite color configuration
xrdb -merge ~/.Xresources.colors

# Vim watches ~/.vimrc.color and reloads itself
# echo "set background=$background" > ~/.vimrc.color

# Rofi
# echo "solarized-$background" > ~/.config/rofi/theme

# For triggering dark themes in GTK apps. Requires `gnome-themes-extra` to be
# installed (for adwaita-dark). This is primarily for Firefox
if [ $background = dark ]; then
  ln -sf ~/.config/xsettingsd.dark ~/.config/xsettingsd;
else
  ln -sf ~/.config/xsettingsd.light ~/.config/xsettingsd;
fi

# Reload
# Update WM background
hsetroot -solid "$(xrdb -query | grep 'desktop.background' | head -n1 | cut -f 2)"

# Update i3
i3-msg reload

killall -HUP xsettingsd

# if [ $background = dark ]; then
#   ln -sf ~/.config/alacritty/auri_dark.toml ~/.config/alacritty/colors.toml;
# else
#   ln -sf ~/.config/alacritty/auri_light.toml ~/.config/alacritty/colors.toml;
# fi
# alacritty msg config "$(cat ~/.config/alacritty/colors.toml)"

# make sure to reload theme
ln -sf ~/.config/kitty/auri_dark.conf ~/.config/kitty/auri_theme.conf;

# FIXME Don't have a decent light theme for kitty
# Update terminal emulator
# if [ $background = dark ]; then
#   ln -sf ~/.config/kitty/auri_dark.conf ~/.config/kitty/auri_theme.conf;
# else
#   ln -sf ~/.config/kitty/auri_light.conf ~/.config/kitty/auri_theme.conf;
# fi

# Reload all kitties
kill -s USR1 $(pidof kitty)
